kind: Service
apiVersion: v1
metadata:
  name: spring-study-svc
spec:
  type: NodePort
  selector:
    app: spring-study
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30081